dist: boinic
language: csharp
solution: NCoreUtils.Backports.sln
mono: none
dotnet: 2.1.807
before_install:
  # explicitly install other targeted SDKs side by side
  - sudo apt-get install dotnet-sdk-3.1
script:
  - dotnet restore
  - dotnet test -c Release -f netcoreapp2.1 NCoreUtils.Backports.Unit